#ifndef TODOLIST_TODOLIST_ERROR_CODE_H__
#define TODOLIST_TODOLIST_ERROR_CODE_H__

typedef enum {
    FAILURE = -1, SUCCESS = 0 /*, FATAL_ERROR = 1*/
} error_t;

#endif // TODOLIST_TODOLIST_ERROR_CODE_H__