# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-4908-周林/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/multi-CPU/CPU.srcs/sources_1/new/RAM.v
      D:/multi-CPU/CPU.srcs/sources_1/new/Data_Selector3.v
      D:/multi-CPU/CPU.srcs/sources_1/new/Data_selector2.v
      D:/multi-CPU/CPU.srcs/sources_1/new/Regfile.v
      D:/multi-CPU/CPU.srcs/sources_1/new/PCj.v
      D:/multi-CPU/CPU.srcs/sources_1/imports/new/Data_selector4.v
      D:/multi-CPU/CPU.srcs/sources_1/new/PC4.v
      D:/multi-CPU/CPU.srcs/sources_1/new/PC01.v
      D:/multi-CPU/CPU.srcs/sources_1/new/CU.v
      D:/multi-CPU/CPU.srcs/sources_1/new/Reg.v
      D:/multi-CPU/CPU.srcs/sources_1/new/InsMem.v
      D:/multi-CPU/CPU.srcs/sources_1/new/PC.v
      D:/multi-CPU/CPU.srcs/sources_1/new/Extend.v
      D:/multi-CPU/CPU.srcs/sources_1/new/ALU.v
      D:/multi-CPU/CPU.srcs/sources_1/new/CPU.v
      D:/multi-CPU/CPU.srcs/sources_1/new/CPU_sim.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top CPU_sim
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter webTalkPath {D:/multi-CPU/CPU.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4908-周林/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
