# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/multi-CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/multi-CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/multi-CPU/CPU.srcs/sources_1/new/RAM.v
  D:/multi-CPU/CPU.srcs/sources_1/new/Data_Selector3.v
  D:/multi-CPU/CPU.srcs/sources_1/new/Data_selector2.v
  D:/multi-CPU/CPU.srcs/sources_1/new/Regfile.v
  D:/multi-CPU/CPU.srcs/sources_1/new/PCj.v
  D:/multi-CPU/CPU.srcs/sources_1/imports/new/Data_selector4.v
  D:/multi-CPU/CPU.srcs/sources_1/new/PC4.v
  D:/multi-CPU/CPU.srcs/sources_1/new/PC01.v
  D:/multi-CPU/CPU.srcs/sources_1/new/CU.v
  D:/multi-CPU/CPU.srcs/sources_1/new/Reg.v
  D:/multi-CPU/CPU.srcs/sources_1/new/InsMem.v
  D:/multi-CPU/CPU.srcs/sources_1/new/PC.v
  D:/multi-CPU/CPU.srcs/sources_1/new/Extend.v
  D:/multi-CPU/CPU.srcs/sources_1/new/ALU.v
  D:/multi-CPU/CPU.srcs/sources_1/new/CPU.v
  D:/multi-CPU/CPU.srcs/sources_1/new/CPU_sim.v
}
synth_design -top CPU_sim -part xc7a35tcpg236-1
write_checkpoint -noxdef CPU_sim.dcp
catch { report_utilization -file CPU_sim_utilization_synth.rpt -pb CPU_sim_utilization_synth.pb }
